AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Deployment of all resources for the spirderweb

Parameters:
  env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  prefix:
    Type: String
    Default: "Spiderweb"
  postgresUser:
    NoEcho: 'true'
    Description: Username for Postgres database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  postgresPassword:
    Type: String
    NoEcho: 'true'
    Description: Password Postgres database access
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.

Resources:
  DataPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./data-pipeline/template.yaml
      Parameters:
        env: !Ref env
        DBUsername: !Ref postgresUser
        DBPassword: !Ref postgresPassword
