AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Deployment of all resources for the spirderweb

Parameters:
  env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

  prefix:
    Type: String
    Default: "Spiderweb"

Resources:
  DataPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./data-pipeline/template.yaml
      Parameters:
        env: !Ref env
