Parameters:
  env:
    Type: String
    AllowedValues:
      - dev
      - prod

Resources:
  AirflowArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "spiderweb-airflow-${env}"
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 7
            Status: Enabled

Outputs:
  ExecutionBucket:
    Description: Bucket that stores intermediate values for airflow
    Value: !Ref AirflowArtifactsBucket
    Export:
      Name: !Sub "${AWS::StackName}-AirflowArtifacts"