version: '3'
services:
  mysql:
    image: mysql:5.7.29
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  neo4j:
    image: neo4j:3.5.3
    ports:
     - "${BOLT_PORT}:7687"
     - "${NEO4J_HTTP_PORT}:7474"
     - "${NEO4J_HTTPS_PORT}:7473"