name: Format Checker

on: [pull-request]

jobs:
  lint-black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Black Code Formatter
      uses: jpetrucciani/black-check@master
      with:
        path: .